services:
  web:
    build: .
    image: youtube-downloader:v1.0
    container_name: youtube-downloader-dev
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/downloads
    tmpfs:
      - /.gunicorn:rw,noexec,nosuid
    user: "1000:1000"
    